// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"github.com/fukuyama012/go-server-layered-sample/db"
	"github.com/fukuyama012/go-server-layered-sample/infra/mysql"
	"github.com/fukuyama012/go-server-layered-sample/usecase"
)

// Injectors from wire.go:

func initExample(hint string) usecase.Example {
	dbDB := db.NewDB(hint)
	example := mysql.NewExample(dbDB)
	usecaseExample := usecase.NewExample(example)
	return usecaseExample
}
